'use client';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import Provaider from '../context/Provider';
import Script from 'next/script';
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_API_MAPS_GOOGLE}&libraries=places`}
          strategy="beforeInteractive"
        />
      </head>
      <body
        style={{
          margin: 0,
          padding: 0,
        }}
        className={inter.className}
      >
        <SessionProvider>
          <ToastContainer />
          <Provaider>
            {children}
          </Provaider>
        </SessionProvider>
      </body>
    </html>
  );
}