import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css" 
import Provaider from '../context/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          padding: 0,
        }} 
        className={inter.className}
        >
          <ToastContainer />
          <Provaider>
            {children}
          </Provaider>
      </body>
    </html>
  )
}
